import styles from '../styles/Home.module.css'
import Head from "next/head";

export default function AboutPage() {
  return (
  <div>
      <div className={styles.mainWrapper}>
          <Head>
              <title>Create Next App</title>
              <meta name="description" content="Generated by create next app" />
              {/*<link rel="icon" href="/favicon.ico" />*/}
              {/*<link rel="icon" href="/pngegg2.ico" />*/}
              <link rel="shortcut icon" href="/pngegg2.png" />
          </Head>

          <main className={styles.main}>
            <div className={styles.mainTitle}>
                <h1 style={{fontSize: '2.5rem'}}>About</h1>
                <h2>This server based on next.js</h2>
            </div>
            <div className={styles.routesBlock}>
              <div className={styles.routes}>
                  <div className={styles.routesTitle}>
                      Learn More
                  </div>
                  <div className={styles.mainList}>
                      <p>To learn more about Next.js, take a look at the following resources:</p>
                      <p><a href="https://nextjs.org/docs">Next.js Documentation</a> - learn about Next.js features and API.</p>
                      <p>  <a href="https://nextjs.org/learn">Learn Next.js</a>Learn Next.js - an interactive Next.js tutorial.</p>
                      <p>You can check out <a href="https://github.com/vercel/next.js/">the Next.js GitHub repository</a> - your feedback and contributions are welcome!</p>
                  </div>

                  <div className={styles.routesTitle}>
                      Deploy on Vercel
                  </div>
                  <div className={styles.mainList}>
                      <p>The easiest way to deploy your Next.js app is to use the <a href="https://vercel.com/new?utm_medium=default-template&filter=next.js&utm_source=create-next-app&utm_campaign=create-next-app-readme">Vercel Platform</a> from the creators of Next.js.</p>
                      <p>Check out our <a href="https://nextjs.org/docs/deployment">Next.js deployment documentation</a> for more details.</p>
                  </div>

              </div>
            </div>
              <div className={styles.mainLink}>
                  <a href="http://localhost:3000/"><h4>Go to main page</h4></a>
              </div>
        </main>
      </div>
  </div>
  )
}