import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from "../Components/Header";
import Routesblock from "../Components/Routesblock"


export default function Home() {
  return (

      <div className={styles.mainWrapper}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="shortcut icon" href="/pngegg2.png" />
        </Head>

        <main className={styles.main}>

          <Header tag_1='h1' main_title_1='Welcome to server for testing' tag_2='h2' main_title_2='(based on Next.js)'/>

          <Routesblock />

        </main>

      </div>

  )
}
