// api.openweathermap.org/data/2.5/weather?q={city name}&appid={API key}


import styles from "../styles/Home.module.css";
import Head from "next/head";

function Weather(props) {
  return (
      <div>
          <div className={styles.mainWrapper}>
          <Head>
              <title>Create Next App</title>
              <meta name="description" content="Generated by create next app" />
              {/*<link rel="icon" href="/favicon.ico" />*/}
              {/*<link rel="icon" href="/pngegg2.ico" />*/}
              <link rel="shortcut icon" href="/pngegg2.png" />
          </Head>


          <main className={styles.main}>
          <div className={styles.mainTitle}>
              <h1>Weather</h1>
              <h2>From <a href="https://openweathermap.org">https://openweathermap.org</a></h2>
          </div>
          <div className={styles.routesBlock}>
              <div className={styles.routes}>
                <div className={styles.routesTitle}>
                    <h3>just now weather in :</h3>
                </div>
                <div className={styles.mainList}>
                    <p>city:&nbsp;&nbsp;{props.city}</p>
                    <p>description:&nbsp;{props.description},</p>
                    <p>temperature:&nbsp;{props.temperature}&deg;C</p>
                </div>
              </div>
          </div>
          {/*<div className={styles.main}>*/}
            {/*  <p style={{fontSize: '2rem'}}>Weather in {props.city}: {props.description}, {props.temperature}&deg;C</p>*/}
          {/*</div>*/}
              <div className={styles.mainLink}>
                  <a href="http://localhost:3000/"><h4>Go to main page</h4></a>
              </div>
        </main>
          </div>
      </div>
  )
}

export async function getStaticProps() {
  const city = process.env.CITY_NAME
  const apiKey = process.env.API_KEY
  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&appid=${apiKey}`

  const res = await fetch(url)
  const json = await res.json()

 return {
    props: {
      city: json.name,
      description: json.weather[0].description,
      temperature: parseInt(json.main.temp -273),

    },
  }
}

export default Weather